app:
    resource: '@AppBundle/Controller/'
    type: annotation

qr_code:
    resource: "@EndroidQrCodeBundle/Resources/config/routes.yaml"
    prefix: /qr-code/generator

fos_user:
    resource: '@AppBundle/Resources/config/routing/fos_user.yaml'

sonata_admin:
    resource: '@AdminBundle/Resources/config/routing/sonata_admin.yaml'